# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

---

# See https://developer.hashicorp.com/consul/docs/k8s/helm for more information
global:
  name: consul
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
server:
  replicas: 1
ui:
  enabled: true
  service:
    type: LoadBalancer
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
