# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

---

# See https://developer.hashicorp.com/consul/docs/k8s/helm for more information
global:
  enabled: true
  name: consul
  datacenter: dc1
  tls:
    enabled: false
  acls:
    manageSystemACLs: true
server:
  enabled: true
  replicas: 3
connectInject:
  enabled: true
ui:
  enabled: true
  service:
    type: LoadBalancer